name: 'lonestar_edw'
version: '1.0.0'

profile: 'lonestar_edw'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  lonestar_edw:
    staging:
      +schema: silver
      +materialized: view
    intermediate:
      +schema: silver
      +materialized: ephemeral
    marts:
      +schema: gold
      +materialized: table
