output "snowflake_iam_user_arn" {
  value       = snowflake_storage_integration_aws.lonestar_s3.describe_output[0].iam_user_arn
  description = "Snowflake-managed IAM user ARN"
}

output "snowflake_external_id" {
  value       = snowflake_storage_integration_aws.lonestar_s3.describe_output[0].external_id
  description = "External ID generated by Snowflake"
}
