USE ROLE ACCOUNTADMIN;

-- CREATE USER TERRAFORM_SVC

GRANT CREATE DATABASE       ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE WAREHOUSE      ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE ROLE           ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE USER           ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT CREATE INTEGRATION    ON ACCOUNT TO ROLE TERRAFORM_ROLE;
GRANT MANAGE GRANTS         ON ACCOUNT TO ROLE TERRAFORM_ROLE;

USE ROLE SECURITYADMIN;
GRANT ROLE TERRAFORM_ROLE TO USER TERRAFORM_SVC;
ALTER USER TERRAFORM_SVC SET DEFAULT_ROLE = TERRAFORM_ROLE;
