name: Terraform CI pipeline

on:
  pull_request:
    paths:
      - "snowflake_infra/**"

jobs:
  tf_ci:
    name: Terraform CI
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ./snowflake_infra/production

      - name: terraform validate
        uses: dflook/terraform-validate@v2
        with:
          path: ./snowflake_infra/production
